### ISSUE TITLE
Improve the result output

### ISSUE THREAD

**Issue by mukeshpanchal27** [swissspidy/wp-plugin-check-action#19]
While reviewing some of the adoption PRs, I came across feedback in this conversation: https://github.com/futtta/autoptimize/issues/412#issuecomment-1871273490. According to the discussion, could we consider updating the result display so that users can identify from which file the errors/notices originate along with the line numbers? Here is an example of the check action output: https://github.com/futtta/autoptimize/actions/runs/7432069708/job/20223464252

> re. the output; it's very verbose, but it is missing what seems to be essential; the file and line number for which the warning/ error was thrown?

**Comment by swissspidy** [comment]
That's just the raw console log output. Every warning/error is filed as an annotation directly in-line within each file. Very useful for PRs. See https://github.com/futtta/autoptimize/actions/runs/7432069708 for a list of files and each warning.

I just commented on that issue to explain it.
