### ISSUE TITLE
Ignore hidden files according the .gitattributes

### ISSUE THREAD

**Issue by pedro-mendonca** [swissspidy/wp-plugin-check-action#24]
Hi @swissspidy 

Thanks for this awesome action :)

I'm starting to use it and I have .dotfiles on the root folder.
I can add an exception as you've mentioned in https://github.com/swissspidy/wp-plugin-check-action/issues/16 for that check, but that might not be a good idea because might fail to check for other hidden files in subfolders.

In my case, I'm deploying to w.org with the 10up/deploy action that uses .gitattributes to ignore the files I've specified on export.

Would it be possible for this action consider the .gitattributes and ignore the files that are ignores on export?

**Comment by swissspidy** [comment]
Hi Pedro 👋 

Thanks for the suggestion!

I assume this is for the Translation Tools plugin? Since you are using a `.distignore` file there, note that the 10up deploy action only uses that one, not `.gitattributes`.

Anyway, it's definitely an interesting use case, and it makes sense at first glance. Plugin Check or this GitHub Action are intended to be used on the final plugin ZIP that ends up on WordPress.org. So it's important that these files are not present.

So yeah, I think adding support for `.gitattributes` / `.distignore` makes sense. I'll just have to think about how best to implement it.

----

PS. I see that you excluded some dist files in https://github.com/pedro-mendonca/Translation-Tools/commit/165213224ebc13568e7f3263c39db02791f58e53 but I still see them in https://plugins.svn.wordpress.org/translation-tools/trunk/. Maybe they need to be deleted manually.

**Comment by pedro-mendonca** [comment]
Hi :)

Actually I didn't start by Translation Tools, but will get to it. On that particular plugin, the exclusion is correct but it wasn't deployed yet. Thanks for noticing that!

I have both `.distignore` and `.gitattributes`, so it fallsback to the first one. But if `.distignore` doesn't exist it can use the `.gitattributes`.

Either way, I's a good idea to support both, with priority to one. I suggest the same priority as in the 10up action. I don't like the idea of ignoring the hidden files check just because of these that are already ignored in the deploy settings.

**Comment by swissspidy** [comment]
> I don't like the idea of ignoring the hidden files check just because of these that are already ignored in the deploy settings.

Agreed, it's yet another list you would have to maintain.

**Comment by pedro-mendonca** [comment]
Another warning that I'm getting is the slug mismatch. Again, it's not usually a problem when you deploy a plugin with the `SLUG` declared in the action. Do you think it's possible to also declare it in the WP Plugin Check action?

**Comment by swissspidy** [comment]
Hmm good question. Normally this would be handled in a build step before running Plugin Check.

What's the slug mismatch in your case?

I suppose I could support it, but that would simply do a `mv <currentdirectory> <desiredslug>` under the hood, which you could just do yourself.

You could also just do this:

```yaml
- name: Checkout repository with correct slug
  uses: actions/checkout@v4
  with:
    path: 'your-desired-slug'
```

Would that work for you?

**Comment by pedro-mendonca** [comment]
I've tested with the Checkout `path` option, also had to add `working-directory` to the composer install action, and it's working now, it's enough for me :)

Here is my current test, passing with the slug warning:
https://github.com/pedro-mendonca/GP-Toolbox/actions/runs/7740260554
It's a simple case mismatch difference in `GP-Toolbox` ≠ `gp-toolbox`

And here is now my test without the slug warning:
https://github.com/pedro-mendonca/GP-Toolbox/actions/runs/7740776727

Thanks!

Still, sorry for poluting this issue with another one. I'ts related but if you prefer, please let me know and we can open another issue.

**Comment by swissspidy** [comment]
> Still, sorry for poluting this issue with another one. I'ts related but if you prefer, please let me know and we can open another issue.

No problem :) I'm glad the method I suggested is working for you. At the moment I don't think it's worth adding a `slug` option in this GitHub Action, but if it becomes a more common request it can be reconsidered.

I'll focus on `.gitattributes` / `.distignore` for now :)

**Comment by pedro-mendonca** [comment]
I've actually changed the approach a bit, inspired by what is done under the hood in the 10up deploy action.
I'm copying the build folder to another using .distignore to exclude the unnecessary files. Then I test only the built files.
So with this approach I don't ignore any tests in the actual Plugin Check :)
https://github.com/pedro-mendonca/Translation-Tools/blob/master/.github/workflows/plugin-check.yml#L65

**Comment by swissspidy** [comment]
Neat! That's exactly what the `build-dir` option is for :)

Also nice to know you can use `.distignore` with `rsync --exclude-from` 💡

**Comment by pedro-mendonca** [comment]
The base idea was from here:
https://github.com/10up/action-wordpress-plugin-deploy/blob/develop/deploy.sh#L94

**Comment by swissspidy** [comment]
Closing this one for now as `rsync` and `build-dir` is a nice workaround. No need to reinvent the wheel :)
